name: Claim
version: 1.0.0
main: dev.objz.claim.Claim
api-version: '1.21'
folia-supported: true
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: true
    BlueMap:
      load: BEFORE
      required: false
